name: pgaa-authentication
channels:
  - conda-forge
dependencies:
  - ipykernel
  - imbalanced-learn ==0.9.1
  - matplotlib ==3.5.2
  - numpy ==1.22.4
  - pandas ==1.4.3
  - scipy ==1.9.0
  - seaborn ==0.11.2
  - scikit-learn ==1.1.2
  - tqdm
  - watermark
  - pip
  - pip:
    - pacmap ==0.6.5
